config/routes.rb
Rails.application.routes.draw do
#portfolios
root to: "welcome#index"
get '/portfolios', to: "portfolios#index", as: "portfolios"
get '/portfolios/new', to: "portfolios#new", as: "new_portfolio"
post '/portfolios', to: "portfolios#create"
get '/portfolios/:id', to: "portfolios#show", as: "portfolio"
get '/portfolios/:id/edit', to: "portfolios#edit", as: "edit_portfolio"
patch '/portfolios/:id', to: "portfolios#update"
delete '/portfolios/:id', to: "portfolios#delete"


#stocks
get '/stocks', to: "stocks#index", as: "stocks"
get '/stocks/:id', to: "stocks#show", as: "stock"
get '/stocks/:id/buy', to: "stocks#buy", as: "buy"
get '/stocks/:id/sell', to: "stocks#sell", as: "sell"



#portstocks
get '/portstocks', to: "portstocks#index", as: "portstocks"
get '/portstocks/buy', to: "portstocks#buy", as: "buy_portstock"
get '/portstocks/sell', to: "portstocks#sell", as: "sell_portstock"
# post '/portstocks', to: "portstocks#create"
post '/portstocks/buy', to: "portstocks#buy_create", as: "buy_create"
post '/portstocks/sell', to: "portstocks#sell_create", as: "sell_create"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :portstocks
    has_many :stocks, through: :portstocks

    

end

app/models/portstock.rb
class Portstock < ApplicationRecord
    belongs_to :portfolio
    belongs_to :stock

   


end

app/models/stock.rb
class Stock < ApplicationRecord
    has_many :portstocks
    has_many :portfolios, through: :portstocks




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :buyable_shares, :current_port, :port_present?

    def buyable_shares(port_id, stock_id)
        cash_available = Portfolio.find(port_id).cash
        current_stock_price = Stock.find(stock_id).price
        cash_available / current_stock_price
    end

    def current_port
        if session[:port_id]
            Portfolio.find(session[:port_id])
        end 
    end

    def port_present?
        !!current_port
    end

    
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    def index
        @portfolios = Portfolio.all
    end

    def new 
        @portfolio = Portfolio.new
    end

    def create 
        portfolio = Portfolio.new(portfolio_params)
        portfolio.cash = 100000
        portfolio.save
        redirect_to portfolio_path(portfolio)
    end

    def show
        @portfolio = Portfolio.find(params[:id])
        @portstocks = @portfolio.portstocks
        session[:port_id] = @portfolio.id
        @portstocks_unique = port_portstocks_unique
        @portstocks_w_shares = portstocks_w_shares
    end

    def edit
        @portfolio = Portfolio.find(params[:id])
    end

    def update
        portfolio = Portfolio.find(params[:id])
        portfolio.update(portfolio_params)
        redirect_to portfolio_path(portfolio)
    end

    def delete
        portfolio = Portfolio.find(params[:id])
        session.destroy
        portfolio.destroy
        redirect_to portfolios_path
    end







private
    def portfolio_params
        params.require(:portfolio).permit(:name, :cash)
    end

    def port_portstocks_unique 
        @portstocks.uniq do |portstock|
            portstock.stock_id
        end
    end

    def portstocks_w_shares
        @ps_uniq_shares = []
        @portstocks_unique.each do |portstock|
            @ps_shares = stocks_in_question(portstock).map do |pstock| 
                pstock.shares
            end
            if @ps_shares.sum > 0
                @ps_uniq_shares << portstock
            end
        end
        @ps_uniq_shares
    end

    def stocks_in_question(portstock)
        @portstocks.select do |ps|
            ps.stock.id == portstock.stock_id
        end
    end


end

app/controllers/portstocks_controller.rb
class PortstocksController < ApplicationController
    helper_method :shares_owned

    def index
        @portstocks = Portstock.all
    end

    def buy 
        @portstock = Portstock.new
    end

    def sell 
        @total_amount_paid_for_stock = total_amount_paid_for_stock
        @shares_owned = shares_owned
        @portstock = Portstock.new
    end
 
    def sell_create
        share_count = params[:portstock][:shares].to_i
        stock_price = Stock.find(session[:stock_id]).price
        total_price = share_count * stock_price
        current_port = Portfolio.find(session[:port_id])
        port_cash = Portfolio.find(session[:port_id]).cash
        if share_count <= shares_owned
            @portstock = Portstock.new(
                stock_id: session[:stock_id], 
                portfolio_id: session[:port_id], 
                shares: -share_count, 
                purchase_price: Stock.find(session[:stock_id]).price)
            @portstock.save
            current_port.cash += total_price
            current_port.save
            redirect_to portfolio_path(session[:port_id])
        else
            flash[:message] = "You don't have enough shares brah!"
            redirect_to sell_portstock_path
        end
    end

    def buy_create
        share_count = params[:portstock][:shares].to_i
        stock_price = Stock.find(session[:stock_id]).price
        total_price = share_count * stock_price
        current_port = Portfolio.find(session[:port_id])
        port_cash = Portfolio.find(session[:port_id]).cash
        if share_count * stock_price <= port_cash
            @portstock = Portstock.new(
                stock_id: session[:stock_id], 
                portfolio_id: session[:port_id], 
                shares: params[:portstock][:shares], 
                purchase_price: Stock.find(session[:stock_id]).price)
            @portstock.save
            current_port.cash -= total_price
            current_port.save
            redirect_to portfolio_path(session[:port_id])    
        else
            flash[:message] = "You do not have enough cash brah!"
            redirect_to buy_portstock_path    
        end
    end

    


    private
    
    def portstock_params 
        params.require(:portstock).permit(:stock_id, :portfolio_id, :shares, :purchase_price)
    end    

    def shares_owned
        portstocks = portfolio_portstock
        stock = portstocks.select{ |portstock| portstock.stock_id == session[:stock_id]}
        shares = stock.map{ |stock| stock.shares}
        shares.sum
    end

    def portfolio_portstock
        portstocks = Portstock.all.select{ |portstock| portstock.portfolio_id == session[:port_id]}
    end

    def negative_shares
        params[:portstock][:shares] = (params[:portstock][:shares]) * -1
    end

    # def current_total_stock_value_owned
    #     stock = portfolio_portstocks.select{ |portstock| portstock.stock_id == session[:stock_id]}
    #     price = stock.map{ |stock| stock.Stocks.price}
    #     shares.sum
    # end

    def total_amount_paid_for_stock
        stocks = portfolio_portstock.select{ |portstock| portstock.stock_id == session[:stock_id]}
        pvalue = stocks.map{ |stock| stock.purchase_price * stock.shares}
        pvalue.sum
    end



end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

    def index
        @stocks = Stock.all
    end

    def show
        @stock = Stock.find(params[:id])
    end

    def buy
        @stock = Stock.find(params[:id])
        session[:stock_id] = @stock.id
        redirect_to buy_portstock_path
    end

    def sell
        @stock = Stock.find(params[:id])
        session[:stock_id] = @stock.id
        redirect_to sell_portstock_path
    end

    
    
    private
    def stock_params
        params.require(:stock).permit(:name, :symbol, :price)
    end

    








end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

    def percent_return(portstock, avg_stockp_paid)
        @per_return = ((portstock.stock.price - avg_stockp_paid).to_f/avg_stockp_paid.to_f)*100
        if @per_return > 0
            content_tag(:td, "#{number_to_percentage(@per_return)}", class: "text-success")
        elsif @per_return < 0
            content_tag(:td, "#{number_to_percentage(@per_return)}", class: "text-danger")
        else @per_return = 0    
            content_tag(:td, "#{number_to_percentage(@per_return)}")
        end     
        #byebug
    end

end

# <td><%= @per_return = ((portstock.stock.price - @avg_stockp_paid).to_f/@avg_stockp_paid).to_f*100
# if @per_return > 0
#     number_to_percentage(@per_return)
# elsif @per_return < 0
#     number_to_percentage(@per_return)
# else @per_return = 0    
#     number_to_percentage(@per_return)
# end     
# %>  
# </td> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyStocks</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="css/application.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
  </head>

  <body>
  <nav class="navbar navbar-expand  navbar-light bg-white topbar mb-4 static-top shadow">
    <ul class= navbar-nav>
      <li class="nav-item navbar-left">
        <a class="sidebar-brand d-flex align-items-center justify-content-center">
          <div class="text-s font-weight-bold text-success text-uppercase"> Fantasy Stocks</div>
        </a>
      </li>  
      <li class="nav-item">  
        <a class="navbar-brand d-flex align-items-center justify-content-center">
          <div class="text-xs font-weight-bold text-secondary text-uppercase navbar-right"> 
          <% if port_present? %>
                    Current Portfolio: <%= current_port.name %>
              <% end %>  
          </div>
        </a>
      </li>  
    </ul>    
  </nav>
    <div class="body_content" >
        <%= yield %>
    </div>
  </body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    
  </body>
</html>

app/views/portfolios/edit.html.erb
<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-8 col-lg-8 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h2 text-gray-900 mb-2">Rename Your Portfolio</h1>
                    <p class="mb-4">Choose a new name for your portfolio.</p>
                    <p class="mb-4">The current name is: <%= @portfolio.name %></p>
                    <%= form_for @portfolio do |f| %>
                        <% f.label "What Would You Like To Call Your Portfolio?" %>
                        <%= f.text_field :name %>
                        <%= f.submit "Update Name", class: "d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" %>
                    <% end %>
                    <br>
                    <p><%= link_to 'Cancel', portfolio_path(session[:port_id]) %>
                </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/portfolios/index.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800">All Portfolios</h1>                   
</div> 



<%= link_to 'Create a New Portfolio', new_portfolio_path, class: "btn btn-primary" %><br>
<br>
<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" >Portfolio Name</th>
                            <th scope="col" ></th>
                        </tr>
                    </thead>  

                    <tbody>
                        <% @portfolios.each do |portfolio| %>
                            <tr scope="row">
                                <td><%= link_to portfolio.name, portfolio_path(portfolio) %></td>
                                <td><%= button_to 'Delete', {action: 'delete', id: portfolio.id}, method: :delete, class: "btn btn-secondary", data: { confirm: "Are you sure?" } %></td>
                            </tr>
                        <%end%>
                    </tbody>        
                </table>     
            </div>
        </div>
    </div>                      
</div>     


    

app/views/portfolios/new.html.erb
<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-8 col-lg-8 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h2 text-gray-900 mb-2">Create A New Portfolio</h1>
                    <p class="mb-4">What would you like to call your portfolio?</p>
                    <%= form_for @portfolio do |f| %>
                        <% f.label :name %><br>
                        <%= f.text_field :name %>
                        <%= f.submit "Create Portfolio", class: "d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm" %>
                    <% end %>
                  </div>
                </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>
</body>

app/views/portfolios/show.html.erb
<%= link_to 'Back to All Portfolios', portfolios_path %><br>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h1 mb-0 text-gray-800"><%= @portfolio.name %></h1>
    <div id="buttons">
        <%= link_to 'Rename This Portfolio', edit_portfolio_path(@portfolio), class: "d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm"  %>
        <%= button_to 'Delete This Portfolio', {action: 'delete', id: @portfolio.id}, method: :delete, class: "d-none d-sm-inline-block btn btn-sm btn-secondary shadow-sm", data: { confirm: "Are you sure?" } %>
    </div>
</div>
<br>
<div class="row">
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Cash Available</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800"><%= number_to_currency(@portfolio.cash) %></div>
                    </div>
                    <div class="col-auto">
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Total Value of Stocks</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800"><%= number_to_currency(@portstocks.map{|ps|ps.shares*ps.stock.price}.sum) %></div>
                    </div>
                    <div class="col-auto">
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-xl-3 col-md-6 mb-4">
              <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                  <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                      <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Value of Portfolio</div>
                      <div class="h5 mb-0 font-weight-bold text-gray-800"><%= number_to_currency(@portfolio.cash + (@portstocks.map{|ps|ps.shares*ps.stock.price}.sum)) %></div>
                    </div>
                    <div class="col-auto">
                    </div>
                  </div>
                </div>
              </div>
            </div>
 
</div> 

<h2><%= link_to 'Buy Stocks', stocks_path, class: "btn btn-primary btn-lg" %></h2>
<br>

<div class="row">
    <div class="col-lg-12">
        <div class="card shadow mb-4">
            <div class="card-body">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th></th>
                            <th>Name</th>
                            <th>Symbol</th>
                            <th>Shares Owned</th>
                            <th>Avg Price Paid per Stock</th>
                            <th>Current Price</th>
                            <th>Total Stock Value</th>
                            <th>% Return</th>

                        </tr>
                    </thead>

                    <tbody>
                        <% @portstocks_w_shares.each do |portstock|%>
                            <tr>
                                <td><%= link_to "Sell", {controller: "stocks", action: "sell", id: portstock.stock.id}, class: "d-none d-sm-inline-block btn btn-sm btn-primary " %> </td>
                                <td><%= portstock.stock.name %></td>
                                <td><%= portstock.stock.symbol %></td>
                                <td><%= 
                                    @x = @portstocks.select{|ps| ps.stock_id == portstock.stock_id}
                                    @ps_shares = @x.map { |pstock| pstock.shares}
                                    @ps_shares.sum %></td>
                                <td><%= 
                                    @y = @portstocks.select{|ps| ps.stock_id == portstock.stock_id}
                                    ps_costs = @y.map { |pstock| pstock.shares * pstock.purchase_price}
                                    number_to_currency(@avg_stockp_paid = ps_costs.sum/@ps_shares.sum) %></td>
                                <td><%= number_to_currency(portstock.stock.price) %></td>
                                <td><%=
                                    @z = @portstocks.select{|ps| ps.stock_id == portstock.stock_id}
                                    @ps_shares = @x.map { |pstock| pstock.shares}
                                    number_to_currency(@total_stock_value = (@ps_shares.sum)*(portstock.stock.price)) %></td>
                                <%= percent_return(portstock, @avg_stockp_paid) %>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>    
        </div>
    </div>
</div>

app/views/portstocks/buy.html.erb
<p><%= link_to 'Back to Portfolio', portfolio_path(session[:port_id]) %><br>
<h1 class="h1 mb-0 text-gray-800">Let's Buy Some Stocks!</h1>


<% if flash[:message] %>
    <div class="alert alert-danger" role="alert">
        "🙅‍♂️<%= flash[:message] %>🙅‍"
    </div>
<% end%>



<p class="p mb-0 text-gray-800">Portfolio: <%= Portfolio.find(session[:port_id]).name %></p><br>
<h2 class="h2 mb-0 text-gray-800"><%= Stock.find(session[:stock_id]).name %></h2>
<p class="p mb-0 text-gray-800">Stock Symbol: <%= Stock.find(session[:stock_id]).symbol %></p>
<br>
<p class="p mb-0 text-gray-800">Cash Available: <%= number_to_currency(Portfolio.find(session[:port_id]).cash) %></p>
<p class="p mb-0 text-gray-800">Stock Current Price: <%= number_to_currency(Stock.find(session[:stock_id]).price) %></p>
<br>

<%= form_for @portstock, url: buy_create_path do |f| %>
    <%= f.label "How many shares would you like to purchase?" %><br>
    <%= f.number_field :shares %>
    <%= f.submit "Buy", class: "btn btn-primary" %>
<% end %>
<p>(You can purchase <%= buyable_shares(session[:port_id], session[:stock_id]) %> shares.)</p>

<p><%= link_to 'Cancel', portfolio_path(session[:port_id]) %><br>

app/views/portstocks/index.html.erb
all transactions
<table style="width:100%">
    <thead>
        <tr>
            <th>Portfolio Name</th>
            <th>Stock Name</th>
            <th>Symbol</th>
            <th>Shares</th>
            <th>Purchase Price</th>
            <th>Cost</th>
        </tr>
    </thead>

    <tbody>
        <% @portstocks.each do |portstock|%>
            <tr>
                <td><%= portstock.portfolio.name %></td>
                <td><%= portstock.stock.name %></td>
                <td><%= portstock.stock.symbol %></td>
                <td><%= portstock.shares %></td>
                <td><%= number_to_currency(portstock.stock.price) %></td>
                <td>$<%= number_to_currency(portstock.stock.price * portstock.shares) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/portstocks/new.html.erb
<h1>Let's Buy Some Stocks!</h1>

<p>Portfolio: <%= Portfolio.find(session[:port_id]).name %></p>
<p>Stock Name: <%= Stock.find(session[:stock_id]).name %></p>
<p>Stock Symbol: <%= Stock.find(session[:stock_id]).symbol %></p>
<p>Stock Purchase Price: <%= Stock.find(session[:stock_id]).price %></p>


<%= form_for @portstock do |f| %>
    <%= f.label "How many shares?" %><br>
    <%= f.number_field :shares %>
    <%= f.submit "Buy"%>
<% end %>

app/views/portstocks/sell.html.erb
<p><%= link_to 'Back to Portfolio', portfolio_path(session[:port_id]) %><br>
</p>
<h1 class="h1 mb-0 text-gray-800">Let's Sell Some Stocks!</h1>



<% if flash[:message] %>
    <div class="alert alert-danger" role="alert">
         "🙅‍♂️<%= flash[:message] %>🙅‍♀️"
    </div>
<% end%>


<p class="p mb-0 text-gray-800">Portfolio: <%= Portfolio.find(session[:port_id]).name %></p><br>
<h2 class="h2 mb-0 text-gray-800"><%= Stock.find(session[:stock_id]).name %></h2>
<p class="p mb-0 text-gray-800">Symbol: <%= Stock.find(session[:stock_id]).symbol %></p>
<br>
<p class="p mb-0 text-gray-800">Current Stock Price: <%= number_to_currency(Stock.find(session[:stock_id]).price) %></p>
<p class="p mb-0 text-gray-800">Average Stock Price Paid: <%= number_to_currency(@total_amount_paid_for_stock / @shares_owned) %> </p>
<p class="p mb-0 text-gray-800">Total Stock Value: <%= number_to_currency(@shares_owned * Stock.find(session[:stock_id]).price) %></p>
<p class="p mb-0 text-gray-800">Total Stock Price Paid: <%= number_to_currency(@total_amount_paid_for_stock) %> </p>
<p class="p mb-0 text-gray-800">Shares Owned: <%= @shares_owned%></p>
<br>


<%= form_for @portstock, url: sell_create_path do |f| %>
    <%= f.label "How many shares would you like to sell?" %><br>
    <%= f.number_field :shares %>
    <%= f.submit "Sell", class: "btn btn-primary"%>
<% end %>

<p><%= link_to 'Cancel', portfolio_path(session[:port_id]) %><br>

app/views/stocks/index.html.erb
<p><%= link_to 'Back to Portfolio', portfolio_path(session[:port_id]) %><br>



<table class="table">
    <thead class="thead-dark">
        <tr>
            <th></th>
            <th>Stock Name</th>
            <th>Symbol</th>
            <th>Price</th>
        </tr>
    </thead>

    <tbody>
        <% @stocks.each do |stock|%>
            <tr>
                <td><%= link_to "Buy", {action: "buy", id: stock.id}, class: "btn btn-primary" %> </td>
                <td><%= stock.name %></td>
                <td><%= stock.symbol %></td>
                <td><%= number_to_currency(stock.price) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/stocks/show.html.erb
<h1><%= @stock.name %> </h1>
<%= @stock.symbol %>

app/views/welcome/index.html.erb
HOME PAGE